version: '3'
services:
  storj:
    build: .
    image: "storj:latest"
    deploy:
      replicas: 0
  satellite:
    build: ./satellite
    image: satellite:latest
  gateway:
    build: ./gateway
    image: gateway:latest
    depends_on:
      - satellite
    deploy:
      replicas: 0
  storagenode:
    build: ./storagenode
    image: storagenode:latest
    depends_on:
      - satellite
    deploy:
      replicas: 10
  uplink:
    build: ./uplink
    image: uplink:latest
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - "~/:/storj"
    deploy:
      placement:
        constraints:
          - node.role == manager
  aws:
    build: ./aws
    image: aws:latest
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - "~/:/aws"
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.role == manager
