FROM anigeo/awscli:latest
RUN aws configure set default.aws_access_key_id SLSKYAYSq8tWYF5gCMVH4i14T25 \
    && aws configure set default.aws_secret_access_key 2vutPoEDFAU8xW1ScJdWpmGmh4ZU \
    && aws configure set default.s3.multipart_threshold 1TB
